const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  getProducts: () => ipcRenderer.invoke('get-products'),
  addProduct: (product) => ipcRenderer.invoke('add-product', product),
  updateProduct: (id, data) => ipcRenderer.invoke('update-product', id, data),
  getCustomers: () => ipcRenderer.invoke('get-customers'),
  addCustomer: (customer) => ipcRenderer.invoke('add-customer', customer),
  updateCustomer: (id, data) => ipcRenderer.invoke('update-customer', id, data),
  deleteCustomer: (id) => ipcRenderer.invoke('delete-customer', id),
  getSuppliers: () => ipcRenderer.invoke('get-suppliers'),
  addSupplier: (supplier) => ipcRenderer.invoke('add-supplier', supplier),
  updateSupplier: (id, data) => ipcRenderer.invoke('update-supplier', id, data),
  getVehicles: () => ipcRenderer.invoke('get-vehicles'),
  addVehicle: (vehicle) => ipcRenderer.invoke('add-vehicle', vehicle),
  updateVehicle: (id, data) => ipcRenderer.invoke('update-vehicle', id, data),
  getGrns: () => ipcRenderer.invoke('get-grns'),
  addGrn: (grnData) => ipcRenderer.invoke('add-grn', grnData),
  getGrnDetails: (id) => ipcRenderer.invoke('get-grn-details', id),
  updateGrn: (id, data) => ipcRenderer.invoke('update-grn', id, data),
  getGrtns: () => ipcRenderer.invoke('get-grtns'),
  addGrtn: (grtnData) => ipcRenderer.invoke('add-grtn', grtnData),
  getGrtnDetails: (id) => ipcRenderer.invoke('get-grtn-details', id),
  updateGrtn: (id, data) => ipcRenderer.invoke('update-grtn', id, data),
  getStockAdjustments: () => ipcRenderer.invoke('get-stock-adjustments'),
  addStockAdjustment: (adj) => ipcRenderer.invoke('add-stock-adjustment', adj),
  getStockMovements: (limit) => ipcRenderer.invoke('get-stock-movements', limit),
  getSales: () => ipcRenderer.invoke('get-sales'),
  getSaleDetails: (id) => ipcRenderer.invoke('get-sale-details', id),
  addSale: (saleData) => ipcRenderer.invoke('add-sale', saleData),
  updateSale: (id, data) => ipcRenderer.invoke('update-sale', id, data),
  getCheques: () => ipcRenderer.invoke('get-cheques'),
  addCheque: (chequeData) => ipcRenderer.invoke('add-cheque', chequeData),
  updateChequeStatus: (data) => ipcRenderer.invoke('update-cheque-status', data),
  getSupplierPayments: () => ipcRenderer.invoke('get-supplier-payments'),
  addSupplierPayment: (paymentData) => ipcRenderer.invoke('add-supplier-payment', paymentData),
  getReportData: () => ipcRenderer.invoke('get-report-data'),
  getCloudSettings: () => ipcRenderer.invoke('get-cloud-settings'),
  saveCloudSettings: (data) => ipcRenderer.invoke('save-cloud-settings', data),
  syncToCloud: () => ipcRenderer.invoke('sync-to-cloud'),
  getUsers: () => ipcRenderer.invoke('get-users'),
  loginUser: (credentials) => ipcRenderer.invoke('login-user', credentials),
  addUser: (userData) => ipcRenderer.invoke('add-user', userData),
  deleteUser: (id) => ipcRenderer.invoke('delete-user', id),
  getPendingApprovals: () => ipcRenderer.invoke('get-pending-approvals'),
  approveItem: (data) => ipcRenderer.invoke('approve-item', data),
  logLocation: (entry) => ipcRenderer.invoke('log-location', entry),
  getLatestLocations: () => ipcRenderer.invoke('get-latest-locations'),
  getLocationTrail: (userId, limit) => ipcRenderer.invoke('get-location-trail', userId, limit),
  getLocationPlayback: (userId, from, to) => ipcRenderer.invoke('get-location-playback', userId, from, to),

  // Phase 1
  getRoutes: () => ipcRenderer.invoke('get-routes'),
  addRoute: (route) => ipcRenderer.invoke('add-route', route),
  getRouteStops: (routeId) => ipcRenderer.invoke('get-route-stops', routeId),
  updateRouteStops: (routeId, stops) => ipcRenderer.invoke('update-route-stops', routeId, stops),
  getDailySchedules: (date) => ipcRenderer.invoke('get-daily-schedules', date),
  addDailySchedule: (sched) => ipcRenderer.invoke('add-daily-schedule', sched),
  getCustomerVisits: (filters) => ipcRenderer.invoke('get-customer-visits', filters),
  addCustomerVisit: (visit) => ipcRenderer.invoke('add-customer-visit', visit),
  ensureCustomerQr: (customerId) => ipcRenderer.invoke('ensure-customer-qr', customerId),
  getCustomerByQr: (qrCode) => ipcRenderer.invoke('get-customer-by-qr', qrCode),
  getRouteCompletion: (scheduleId) => ipcRenderer.invoke('get-route-completion', scheduleId),

  // Phase 2
  getCategories: () => ipcRenderer.invoke('get-categories'),
  addCategory: (cat) => ipcRenderer.invoke('add-category', cat),
  deleteCategory: (id) => ipcRenderer.invoke('delete-category', id),
  getBrands: () => ipcRenderer.invoke('get-brands'),
  addBrand: (brand) => ipcRenderer.invoke('add-brand', brand),
  deleteBrand: (id) => ipcRenderer.invoke('delete-brand', id),
  getWarehouses: () => ipcRenderer.invoke('get-warehouses'),
  addWarehouse: (wh) => ipcRenderer.invoke('add-warehouse', wh),
  getWarehouseStock: () => ipcRenderer.invoke('get-warehouse-stock'),
  addStockTransfer: (t) => ipcRenderer.invoke('add-stock-transfer', t),
  getStockTransfers: () => ipcRenderer.invoke('get-stock-transfers'),
  getPurchaseOrders: () => ipcRenderer.invoke('get-purchase-orders'),
  addPurchaseOrder: (po) => ipcRenderer.invoke('add-purchase-order', po),
  getPurchaseOrderDetails: (id) => ipcRenderer.invoke('get-purchase-order-details', id),
  getPurchaseReturns: () => ipcRenderer.invoke('get-purchase-returns'),
  addPurchaseReturn: (ret) => ipcRenderer.invoke('add-purchase-return', ret),
  getLowStockProducts: () => ipcRenderer.invoke('get-low-stock-products'),

  // Phase 3
  getQuotations: () => ipcRenderer.invoke('get-quotations'),
  addQuotation: (q) => ipcRenderer.invoke('add-quotation', q),
  convertQuotationToSo: (id) => ipcRenderer.invoke('convert-quotation-to-so', id),
  getSalesOrders: () => ipcRenderer.invoke('get-sales-orders'),
  convertSoToInvoice: (id) => ipcRenderer.invoke('convert-so-to-invoice', id),
  getDeliveryNotes: () => ipcRenderer.invoke('get-delivery-notes'),
  addDeliveryNote: (dn) => ipcRenderer.invoke('add-delivery-note', dn),
  getCustomerPayments: () => ipcRenderer.invoke('get-customer-payments'),
  addCustomerPayment: (p) => ipcRenderer.invoke('add-customer-payment', p),
  getCashBook: () => ipcRenderer.invoke('get-cash-book'),
  addCashBookEntry: (e) => ipcRenderer.invoke('add-cash-book-entry', e),
  getBankTransactions: () => ipcRenderer.invoke('get-bank-transactions'),
  addBankTransaction: (t) => ipcRenderer.invoke('add-bank-transaction', t),
  getIncomeExpenses: () => ipcRenderer.invoke('get-income-expenses'),
  addIncomeExpense: (e) => ipcRenderer.invoke('add-income-expense', e),
  getPromotions: () => ipcRenderer.invoke('get-promotions'),
  addPromotion: (p) => ipcRenderer.invoke('add-promotion', p),
  getCustomerStatement: (id) => ipcRenderer.invoke('get-customer-statement', id),
  getSupplierStatement: (id) => ipcRenderer.invoke('get-supplier-statement', id),

  // Phase 4
  getSyncOutbox: () => ipcRenderer.invoke('get-sync-outbox'),
  enqueueSync: (item) => ipcRenderer.invoke('enqueue-sync', item),
  flushSyncOutbox: () => ipcRenderer.invoke('flush-sync-outbox'),

  // Phase 5
  getGeofences: () => ipcRenderer.invoke('get-geofences'),
  addGeofence: (g) => ipcRenderer.invoke('add-geofence', g),
  getVehicleExpenses: (vehicleId) => ipcRenderer.invoke('get-vehicle-expenses', vehicleId),
  addVehicleExpense: (e) => ipcRenderer.invoke('add-vehicle-expense', e),
  getVehicleFuel: (vehicleId) => ipcRenderer.invoke('get-vehicle-fuel', vehicleId),
  addVehicleFuel: (f) => ipcRenderer.invoke('add-vehicle-fuel', f),
  getVehicleMaintenance: (vehicleId) => ipcRenderer.invoke('get-vehicle-maintenance', vehicleId),
  addVehicleMaintenance: (m) => ipcRenderer.invoke('add-vehicle-maintenance', m),

  // Phase 6
  addAuditLog: (log) => ipcRenderer.invoke('add-audit-log', log),
  getAuditLogs: () => ipcRenderer.invoke('get-audit-logs'),
  getNotifications: (userId) => ipcRenderer.invoke('get-notifications', userId),
  addNotification: (n) => ipcRenderer.invoke('add-notification', n),
  markNotificationRead: (id) => ipcRenderer.invoke('mark-notification-read', id),
  backupDatabase: () => ipcRenderer.invoke('backup-database'),
  getExtendedReport: (filters) => ipcRenderer.invoke('get-extended-report', filters),
});
